import CoreGraphics

/// The effect strips as the importer measured them: frames a sheet, where its art sits
/// in the cell (0 on the bottom edge, the feet line's share, or 0.5 centred), and which
/// are grey, to be toned in the player's energy colour. Generated by
/// Tools/import_sprites.py; don't edit.
enum EffectSheets {
    static let frames: [String: Int] = [
        "esper_charge": 82,
        "esper_particle": 22,
        "esper_spark": 9,
        "esper_spark2": 10,
        "esper_spark3": 7,
        "fire_charge": 12,
        "fire_charge2": 14,
        "fire_dash": 13,
        "fire_explosion": 16,
        "fire_jump": 22,
        "fire_particle": 17,
        "fire_skid": 22,
        "fire_trail": 11,
        "fire_wallspark": 11,
        "fireball_summon": 22,
        "flashspark": 9,
        "flashspark2": 22,
        "ice_jumpspark": 22,
        "jumpspark": 9,
        "lightning1": 25,
        "lightning2": 25,
        "lightning3": 25,
        "lightning4": 25,
        "lightning_charge": 8,
        "lightning_jump": 8,
        "lightning_particle": 20,
        "lightning_particle2": 13,
    ]

    static let anchorY: [String: CGFloat] = [
        "esper_charge": 0.5000,
        "esper_particle": 0.5000,
        "esper_spark": 0.0000,
        "esper_spark2": 0.5000,
        "esper_spark3": 0.0625,
        "fire_charge": 0.5000,
        "fire_charge2": 0.5000,
        "fire_dash": 0.0000,
        "fire_explosion": 0.5000,
        "fire_jump": 0.0000,
        "fire_particle": 0.5000,
        "fire_skid": 0.0000,
        "fire_trail": 0.0000,
        "fire_wallspark": 0.5000,
        "fireball_summon": 0.5000,
        "flashspark": 0.5000,
        "flashspark2": 0.5000,
        "ice_jumpspark": 0.0000,
        "jumpspark": 0.0000,
        "lightning1": 0.0000,
        "lightning2": 0.0000,
        "lightning3": 0.0000,
        "lightning4": 0.0000,
        "lightning_charge": 0.5000,
        "lightning_jump": 0.0625,
        "lightning_particle": 0.5000,
        "lightning_particle2": 0.5000,
    ]

    static let toned: Set<String> = [
        "esper_charge",
        "esper_particle",
        "esper_spark",
        "esper_spark2",
        "esper_spark3",
        "flashspark2",
        "ice_jumpspark",
        "jumpspark",
        "lightning_charge",
        "lightning_jump",
        "lightning_particle",
        "lightning_particle2",
    ]
}
